web-mileem/config/routes.rb
Rails.application.routes.draw do

  get 'statistics/spaces_distribution'

  get 'statistics/near_prices'

  post 'payment/notification'
  
  devise_for :users

  get 'publications/jsonifier/:id' => 'publications#jsonifier'
  get 'publications/search' => 'publications#search'
  get 'publications/:id/preview', to: 'publications#preview', as: 'preview_publication'
  get 'publications/:id/uploads', to: 'publications#uploads', as: 'uploads_publication'
  get 'publications/:id/stop', to: 'publications#stop', as: 'stop_publication'
  get 'publications/:id/finish', to: 'publications#finish', as: 'finish_publication'
  get 'publications/:id/active', to: 'publications#active', as: 'active_publication'
  get 'publications/:id/republicate', to: 'publications#republicate', as: 'republicate'
  post 'publications/:id/republicate', to: 'publications#save_republicate'

  resources :plans
    match 'plans' => "plans#index", :as => :plans_index, via: [:get, :post]

  get 'help' => "help#index", :as => :help

  resources :uploads
  resources :publications do
    resources :uploads, :only => [:create]
    collection do
      get :reset_filterrific
    end
  end
  
  match "publications/payment_return/:id/:status" => "publications#payment_return", :as => :payment_return, :via => [:get,:post]

  get 'uploads/:id/delete', to: 'uploads#destroy', as: 'uploads_destroy'

  post 'video_uploads/create/:publication_id', to: 'video_uploads#create', as: 'video_uploads_publication'
  post 'video_uploads/destroy/:id', to: 'video_uploads#destroy', as: 'destroy_video_uploads_publication'

  root 'welcome#index'

end

web-mileem/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
	<% if msg.is_a?(String) %>
		<div class="alert alert-<%= name.to_s == 'notice' ? 'success' : (name.to_s == 'warning') ? 'warning' : 'danger' %>">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<%= content_tag :div, msg, :id => "flash_#{name}" %>
		</div>
	<% elsif msg.is_a?(Array) %>
			<div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				<%= content_tag :div, msg.join(" - "), :id => "flash_#{name}" %>
			</div>		
	<% end %>
<% end %>

web-mileem/app/views/layouts/_navigation.html.erb
<nav id="main_navbar" class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			
		</div>
		<div class="navbar-collapse collapse navbar-inverse-collapse">
			<ul class="nav navbar-nav navbar-left">
				<%= image_tag "logo-mileem-barra.png" , :width=>"100px", :height=>"50px" %>
			</ul>
			<ul class="nav navbar-nav navbar-left">
				<li><%= link_to 'Inicio', root_path, class: "navbar-brand" %></li>
				<%= render 'layouts/navigation_links' %>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Planes", plans_path %><li>
				<li><%= link_to "Ayuda", help_path %><li>
				<% if user_signed_in? %>
					<li><%= link_to "Nueva publicación", new_publication_path %><li>
					<li><%= link_to "Mis publicaciones", publications_path %><li>

					<li><%= link_to current_user.email, edit_user_registration_path %><li>
					<li class="divider"></li>
					<li><%= link_to "Salir", destroy_user_session_path, :method => :delete  %></li>
				<% else %>
					<li><%= link_to "Registrarse", new_user_registration_path %></li>
					<li><%= link_to "Entrar", new_user_session_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

web-mileem/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

web-mileem/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Web Mileem" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Web Mileem" %>">
    <%= stylesheet_link_tag 'application', debug: true %>
    <%= stylesheet_link_tag "bootstrap-ubuntu", debug: true %>
    <%= javascript_include_tag 'application', debug: true %>
    <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&language=es&key=<%= ENV["GOOGLE_KEY"]%>&libraries=places">
    </script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>