web-mileem/config/routes.rb
Rails.application.routes.draw do

  get 'statistics/spaces_distribution'

  get 'statistics/near_prices'

  post 'payment/notification'
  
  devise_for :users

  get 'publications/jsonifier/:id' => 'publications#jsonifier'
  get 'publications/search' => 'publications#search'
  get 'publications/:id/preview', to: 'publications#preview', as: 'preview_publication'
  get 'publications/:id/uploads', to: 'publications#uploads', as: 'uploads_publication'
  get 'publications/:id/stop', to: 'publications#stop', as: 'stop_publication'
  get 'publications/:id/finish', to: 'publications#finish', as: 'finish_publication'
  get 'publications/:id/active', to: 'publications#active', as: 'active_publication'
  get 'publications/:id/republicate', to: 'publications#republicate', as: 'republicate'
  post 'publications/:id/republicate', to: 'publications#save_republicate'

  resources :plans
    match 'plans' => "plans#index", :as => :plans_index, via: [:get, :post]

  get 'help' => "help#index", :as => :help

  resources :uploads
  resources :publications do
    resources :uploads, :only => [:create]
    collection do
      get :reset_filterrific
    end
  end
  
  match "publications/payment_return/:id/:status" => "publications#payment_return", :as => :payment_return, :via => [:get,:post]

  get 'uploads/:id/delete', to: 'uploads#destroy', as: 'uploads_destroy'

  post 'video_uploads/create/:publication_id', to: 'video_uploads#create', as: 'video_uploads_publication'
  post 'video_uploads/destroy/:id', to: 'video_uploads#destroy', as: 'destroy_video_uploads_publication'

  root 'welcome#index'

end

web-mileem/app/controllers/publications_controller.rb
# -*- encoding : utf-8 -*-
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy, :uploads, :jsonifier, :stop, :finish, :active , :preview]
  before_action :authorize_update, only: [:edit, :update, :destroy, :uploads] #permisos del pundit
  before_action :authorize_read, only: [:show]
  before_filter :authenticate_user!, except: [:search, :jsonifier, :preview] # permisos del devise
  skip_before_action :verify_authenticity_token

  @@currency_conversion = {"USD" => {"USD" => 1, "$" => 10}, "$" => {"USD" => 0.1, "$" => 1}}

  # GET /publications
  # GET /publications.json
  def index
    @filterrific = Filterrific.new(Publication, params[:filterrific])
    number_status = Publication.statuses[:republished]
    @publications = Publication.filterrific_find(@filterrific).
    where("user_id = ? AND status <> ? AND payment_status = ?", current_user.id, number_status, "Realizado").paginate(page: params[:page])

    respond_to do |format|
      format.html { render :index}
      format.js  
      format.json { render :json => @publications.to_a.map{ |p| p.to_json_for_index }.to_json }
    end
  end

  def reset_filterrific
    session[:filterrific_publications] = nil
    redirect_to :action => :index
  end

  def uploads
    @uploads = @publication.uploads
    respond_to do |format|
      format.html { render :upload}
      format.json { render json: @uploads.map{|upload| upload.to_jq_upload } }
    end
  end  
    
  # GET /publications/1
  # GET /publications/1.json
  def show
    render :show
  end

  def preview
    if(@publication.isAvailable and (@publication.payment_status == "Realizado"))
      render :preview
    else
      render :file => "#{Rails.root}/public/404.html",  :status => 404
    end  
  end

  # GET /publications/new
  def new
    @publication = Publication.new
    pesos = Currency.where(name: "Pesos").first
    @publication.currency_id = pesos.id
    @publication.payment_status = "No realizado"
    @publication.effective_date = Date.today.strftime("%d/%m/%Y")
  end  

  # GET /publications/1/edit
  def edit
  end

  # GET /publications/republicate
  def republicate
    old_publication = Publication.find(params[:id])
    @publication_data = old_publication.attributes
    # Si republica antes de que pase un mes del vencimiento/finalizacion de la publicacion vieja
    @has_discount = (Date.today < old_publication.end_date + 1.month)
    # Limpio campos de la publicacion vieja
    ["id", "created_at", "updated_at", "status", "end_date"].each { |k| @publication_data.delete k }
    @publication = Publication.new(@publication_data)
    pesos = Currency.where(name: "Pesos").first
    @publication.effective_date = Date.today.strftime("%d/%m/%Y")
  end

  # POST /publications/republicate
  def save_republicate
    @publication = Publication.new(publication_params)    
    @publication.user_id = current_user.id
    @publication.end_date = @publication.effective_date + @publication.plan.duration.months
    
    # Si el nuevo plan elegido es gratuito, pongo la publicacion como paga
    if (@publication.plan.id == Plan.get_free_plan_id)
      @publication.payment_status = "Realizado" 
    else
      @publication.payment_status = "No realizado"
    end
    
    respond_to do |format|
      if @publication.save
        @publication.available!
        # Como mucho, traigo el limite del nuevo plan... Extasis!
        Upload.where(publication_id: params[:old_publication_id]).
        limit(@publication.plan.number_images_allowed ).each do |upload_old_publication|
           # Le asigno el ID de la publicacion nueva
           upload_old_publication.publication_id = @publication.id
           upload_old_publication.save
        end

        # Si el nuevo plan permite videos
        if @publication.plan.number_videos_allowed > 0
          VideoUpload.where(publication_id: params[:old_publication_id]).each do |video_old_publication|
            video_old_publication.publication_id = @publication.id
            video_old_publication.save
          end
        end
        old_publication = Publication.find(params[:old_publication_id])
        old_publication.republished!  
        
        # Check if has discount
        @has_discount = (Date.today < old_publication.end_date + 1.month)
        if (old_publication.plan.priority < @publication.plan.priority)
          flash["warning"] = 'Al obtener un plan inferior al actual se seleccionaron las primeras 
          imágenes y video que cumplen con la cantidad permitida por el nuevo plan.'
          url_to_redirect = publication_url(@publication)
          if (@publication.plan.id != Plan.get_free_plan_id)
            url_to_redirect = @publication.url_de_pago(@publication.plan.id, @has_discount)
          end
          format.html { redirect_to url_to_redirect }
          format.json { render :show, status: :created, location: @publication }
        else
          if (@publication.plan.id != Plan.get_free_plan_id)
            format.html { redirect_to @publication.url_de_pago(@publication.plan.id, @has_discount) }
          else
            format.html { redirect_to @publication, notice: 'La publicación fue republicada exitosamente.' }  
          end
          
          format.json { render :show, status: :created, location: @publication }
        end
      else
        format.html { render :action=>'republicate', :id=> params[:old_publication_id] }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)
    @publication.user_id = current_user.id
    @publication.end_date = @publication.effective_date + @publication.plan.duration.months
    
    @publication.payment_status = "No realizado"
    # Los planes gratuitos se inicializan en pagos
    @publication.payment_status = "Realizado" if (@publication.plan.id == Plan.get_free_plan_id)

    respond_to do |format|
      if @publication.save
        url_to_redirect = "/publications/payment_return/#{@publication.id}/1"
        if (@publication.plan.id != Plan.get_free_plan_id)
          url_to_redirect = @publication.url_de_pago
        end
          
        @publication.available!
        format.html { redirect_to url_to_redirect }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      oldPlan = Publication.find(@publication.id).plan
      newPlan = Plan.find(publication_params["plan_id"])
      
      #Solo se puede hacer upgrade 
      if(newPlan.priority > oldPlan.priority)
        flash[:error] = "No se puede obtener un plan inferior al actual"
        render :edit 
        return
      end

      # Conservo el plan hasta que se cambie en el payment_controller
      params[:publication][:plan_id] = oldPlan.id

      url_to_redirect = "/publications/payment_return/#{@publication.id}/4"
      #si es upgrade tiene que pagar
      if(newPlan.priority < oldPlan.priority)
        url_to_redirect = @publication.url_de_pago(newPlan.id)
      end

      if(!@publication.isActive)
        @publication.end_date = publication_params["effective_date"].to_date + newPlan.duration.months
      else
         @publication.end_date = Date.today + newPlan.duration.months
      end  
      if @publication.update(publication_params)
        format.html { redirect_to url_to_redirect }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # 1: success, 2: pending, 3: failure, 4: update without payment
  def payment_return
    url = root_url
    if (params[:status] == "1")
      @publication = Publication.find(params[:id])
      url = publication_url(@publication)
      flash[:notice] = "La publicacion ha sido creada correctamente."
    elsif (params[:status] == "2")
      url = publications_url
      flash[:notice] = "El pago de la publiacción esta pendiente. Al completarse exitosamente el mismo, la publicación quedará creada correctamente."
    elsif (params[:status] == "3")
      url = publications_url
      flash[:error] = "El pago de la publiacción no pudo completarse correctamente."
    elsif (params[:status] == "4")
      @publication = Publication.find(params[:id])
      url = publication_url(@publication)
      flash[:notice] = "La publicación fue actualizada exitosamente."
    end
    redirect_to url
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'La publicación fue destruida exitosamente.' }
      format.json { head :no_content }
    end
  end

  def stop 
    if(@publication.isActive && @publication.available?)
      @publication.stopped!
      redirect_to publications_path
    end     
  end  

  def active
    if(@publication.isActive && @publication.stopped?)
      @publication.available!
      redirect_to publications_path
    end    
  end 

  def finish
    if(@publication.isActive && @publication.available?)
      @publication.end_date = Date.today
      @publication.finished!
      @publication.save
      redirect_to publications_path
    end    
  end 

  def jsonifier
    respond_to do |format|
      format.json { render :json => @publication.to_json}
    end
  end



  # GET /publications/search.json?param1=x&param2=y...
  def search
    @publications = Publication.all.to_a.map!{|p| p.to_json}
    Rails.logger.info "Publicaciones total: #{@publications.size}"

web-mileem/app/helpers/publications_helper.rb
# -*- encoding : utf-8 -*-
module PublicationsHelper
end

web-mileem/app/views/publications/_confirmFinishModal.html.erb
<div class="modal fade" id='<%= "myModal_#{publication.id}" %>' tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Finalizar Publicación</h4>
      </div>
      <div class="modal-body">
        ¿Esta usted seguro que desea finalizar la publicación?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <%= button_to finish_publication_path(publication) , class: "btn btn-danger", :method => :get do %>Finalizar<% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

web-mileem/app/views/publications/_list.html.erb
<%# app/views/publicactions/_list.html.erb %>

<div id="results">
 <table class="table table-bordered table-hover table-condensed">
  <thead class="headingListar">
    <tr>
      <th>Fecha Publicación</th>
      <th>Fecha Vencimiento</th>
      <th>Dirección</th>
      <th>Barrio</th>
      <th>Tipo de Inmueble</th>
      <th>Plan</th>
      <th>Tipo de Operacion</th>
      <th>Precio</th>
      <th>Estado</th>
      <th class="actionsColumn">Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% publications.each do |publication| %>
      <tr>
        <td><%= publication.effective_date.strftime("%d/%m/%Y") %></td>
        <td><%= publication.end_date.strftime("%d/%m/%Y") %></td>
        <td><%= publication.address %></td>
        <td><%= publication.neighbourhood.name  if publication.neighbourhood %></td>
        <td><%= publication.property_type.name  if publication.property_type %></td>
        <td><%= publication.plan.name  if publication.plan %></td>
        <td><%= publication.operation %></td>
        <td class="oneLineColumn"><%= publication.currency.abreviatura %> <%= publication.price %></td>
        <td><%= publication.get_current_status %></td>

        <td class="actionsColumn">
          <% if(publication.isActive) %>
            
            <% if(publication.available?) %>
              <%= button_to stop_publication_path(publication) , class: "btn btn-default btn-xs", :method => :get do %>
                <span class="glyphicon glyphicon-pause" title="Pausar"></span>
              <% end %>

              <a class="btn btn-default btn-xs" data-target="#myModal_<%= publication.id %>" data-toggle="modal" href="#">
                  <span class="glyphicon glyphicon-ban-circle" title="Finalizar"></span>
              </a>  
             <%= render partial: 'publications/confirmFinishModal', locals: {publication: publication}  %>
            
            <% end %>
            
            <% if(publication.stopped?) %>
              <%= button_to active_publication_path(publication) , class: "btn btn-default btn-xs", :method => :get do %>
                <span class="glyphicon glyphicon-play" title="Activar"></span>
              <% end %>
            <% end %>
          <% end %>
          <%= button_to publication , class: "btn btn-default btn-xs", :method => :get do %>
            <span class="glyphicon glyphicon-eye-open " title="Ver Publicación"></span>
          <% end %>
          
          <% if(!publication.finished? && (publication.end_date > Date.today)) %>          
              <%= button_to edit_publication_path(publication) , class: "btn btn-default btn-xs",:method => :get do %>
              <span class="glyphicon glyphicon-edit" title="Editar Publicación"></span>
              <% end %>
          <% end %>

          <% if policy(publication).delete? %>
	          <%= button_to publication, class: "btn btn-danger btn-xs", method: :delete, data: {confirm: '¿Esta usted seguro que quiere eliminar la publicación?' } do %>
	            <span class="glyphicon glyphicon-remove-circle" title="Eliminar Publicación"></span>
	          <% end %>
          <% end %>     

          <% if(policy(publication).republish?) %>  
            <%= button_to republicate_path(publication),class: "btn btn-success btn-xs", method: :get do %>
              <span class="glyphicon glyphicon-repeat" title="Republicar"></span>
            <% end %>
          <% end %>  
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate publications, renderer: BootstrapPagination::Rails  %>
</div>

web-mileem/app/views/publications/edit.html.erb
<div class="page-header">
  <h1>Editar publicación</h1>
</div>
<%= render :partial => 'form', :locals => {:modoEdicion => true} %>

web-mileem/app/views/publications/index.html.erb
<div class="page-header">
  <h1>Mis Publicaciones</h1>
</div>

<%= form_for @filterrific do |f| %>
  <div class="row"> 
   <div class="col-md-3">
    Fecha Desde
     <div class="input-group">
    <%= f.text_field :date_at_gte, :class => 'form-control', 'data-behaviour' => 'datepicker', 
     "data-date-format" => "dd/mm/yyyy" %>
     <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
      </div>
  </div>
  <div class="col-md-3">
    Fecha Hasta
     <div class="input-group">
    <%= f.text_field(:date_at_lt, :class => 'form-control','data-behaviour' => 'datepicker', 
     "data-date-format" => "dd/mm/yyyy" ) %>
     <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
      </div>
  </div> 
  <div class="col-md-3">
    Barrio  
    <%= f.collection_select(:with_neighbourhood_id, Neighbourhood.all , :id, :name, {:prompt   => "Seleccione una opción"}, { :class =>"form-control" } ) %>
  </div>
</div>
<div class="row">
  <div class="col-md-3">
    Precio Desde
    <%= f.number_field :price_gte, :class => 'form-control', step: 0.01 , min: 0 %>
  </div>
  <div class="col-md-3">
    Moneda
    <div class="radio">
      <label class="radio-inline">
        <%= f.radio_button :currency_filter_id , 0 , :checked => 'checked'  %><p> Ambos </p>
      </label>
      <% Currency.all.each do |c| %>
      <label class="radio-inline">
        <%= f.radio_button :currency_filter_id , c.id %> <p> <%= c.abreviatura %></p>
      </label>
    <% end %>  
    </div>   
  </div>
  <div class="col-md-3">
    Tipo de Operación
    <div class="radio">
      <label class="radio-inline">
        <%= f.radio_button :operation_search, "Ambos", :checked => 'checked' %><p>Ambos</p>
      </label>
      <label class="radio-inline">
        <%= f.radio_button :operation_search, "Alquiler" %><p>Alquiler</p>
      </label>
      <label class="radio-inline">  
        <%= f.radio_button :operation_search, "Venta" %><p>Venta</p>
      </label>
    </div>   
  </div> 
</div>  
  <div>
    <%= link_to(
      'Limpiar',
      reset_filterrific_publications_path,
    ) %>
  </div>
<% end %>

<br>
<%= render partial: 'publications/list', locals: {publications: @publications}  %>

<br>

<script type="text/javascript" >

$('#filterrific_date_at_gte').datepicker( {language: "es", autoclose: true,todayHighlight: true}).on('changeDate', 
	function (selected) {
        startDate = new Date(selected.date.valueOf());
        startDate.setDate(startDate.getDate(new Date(selected.date.valueOf())));
        $('#filterrific_date_at_lt').datepicker('setStartDate', startDate);
    });

$('#filterrific_date_at_lt').datepicker( {language: "es", autoclose: true,todayHighlight: true}).on('changeDate', 
	function (selected) {
        endDate = new Date(selected.date.valueOf());
        endDate.setDate(endDate.getDate(new Date(selected.date.valueOf())));
        $('#filterrific_date_at_gte').datepicker('setEndDate', endDate);
    });;

</script>

web-mileem/app/views/publications/index.js.erb
<% js = escape_javascript(
  render(
    :partial => 'list',
    :locals => { :publications => @publications }
  )
) %>
$("#results").html("<%= js %>");

web-mileem/app/views/publications/new.html.erb
<div class="page-header">
  <h1>Crear publicación</h1>
</div>
<%= render :partial => 'form', :locals => {:modoEdicion => false} %>

web-mileem/app/views/publications/show.html.erb
<div class="page-header">
  <h1>Publicación</h1>
</div>


<div class="row">
  <div class="col-md-4">
  	<div class="mediaTypeLink" onclick="showPhotos()">FOTOS</div><div class="mediaTypeLink" onclick="showVideo()">VIDEO</div>
    <div class="mediaContainer" id="mediaContainer">
	    <div id="myCarousel" class="carousel slide">
	      <ol class="carousel-indicators">
	        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
	        <% (1..(@publication.uploads.size()- 1)).each do |i| %>
	          <li data-target="#myCarousel" data-slide-to=<%= i.to_i %> ></li>
	        <% end %>   
	      </ol>
	      <div class="carousel-inner">
	        <% if(@publication.uploads.size() > 0) %>
	          <div class="item active" style="height: 300px">
	            <img src="<%= @publication.uploads.first().upload %>" style="width:100%;height:100%;" />
	          </div>
	          <% @publication.uploads.drop(1).each do |u| %>
	            <div class="item" style="height: 300px">
	              <img src="<%= u.upload %>" style="width:100%;height:100%;" />
	            </div>
	        <% end %>
	        <% else %>
	          <div class="item active">
	            <%= image_tag "no_foto.jpg" , :width=>"100%", :height=>"100%" %>
	          </div>
	        <% end %>   
	      </div>
	      <!-- Carousel nav -->
	      <a class="carousel-control left" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
	      <a class="carousel-control right" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
	    </div>
	    
	    <!-- VIDEO -->
	    <div id="videoContainer" style="display:none">
	    	<% if (@publication.video_uploads.size() > 0) %>
				<%= video_tag @publication.video_uploads.first().video_url.to_s, :controls => true, :width=>"100%", :height=>"100%" %>
			<% else %>
				<%= image_tag "no_foto.jpg" , :width=>"100%", :height=>"100%" %>
			<% end %>
	    </div>
    </div>
  </div>

  <h2><strong><%= @publication.address %></strong></h2>
  <div class="col-md-4">
    <dl class="dl-horizontal">
      <dt><strong>Plan</strong></dt>
      <dd><%= @publication.plan.name %></dd>
      <dt><strong>Fecha de publicación</strong></dt>
      <dd><%= @publication.effective_date %></dd>
      <dt><strong>Fecha de vencimiento</strong></dt>
      <dd><%= @publication.end_date %></dd>
      <dt><strong>Barrio</strong></dt>
      <dd><%= @publication.neighbourhood.name %></dd>
      <dt><strong>Tipo de propiedad</strong></dt>
      <dd><%= @publication.property_type.name if (@publication.property_type) %></dd>
      <dt><strong>Precio (<%= @publication.currency.abreviatura %>)</strong></dt>
      <dd><%= @publication.price %></dd>
      <dt><strong>Expensas (<%= @publication.currency.abreviatura %>)</strong></dt>
      <dd><%= @publication.expenses %></dd>
      <dt><strong>Descripción</strong></dt>
      <dd><%= @publication.description %></dd>
    </dl>     
  </div>

  <div class="col-md-4">
    <dl class="dl-horizontal">
      <dt><strong>Tipo</strong></dt>
      <dd><%= @publication.operation %></dd>
      <dt><strong>Piso</strong></dt>
      <dd><%= @publication.floor %></dd>
      <dt><strong>Departamento</strong></dt>
      <dd><%= @publication.apartment %></dd>
      <dt><strong>Ambientes</strong></dt>
      <dd><%= @publication.number_spaces %></dd>
      <dt><strong>Superficie (m2)</strong></dt>
      <dd><%= @publication.surface %></dd>
      <dt><strong>Antiguedad (años) </strong></dt>
      <dd><%= @publication.antiquity %></dd>
      <dt><strong>Información adicional</strong></dt>
      <dd><%= @publication.additional_info %></dd>
    </dl>     
  </div>
</div>

<div class="row">
  <div class="col-md-8 col-md-offset-4">
      <% if policy(@publication).upload_video? %>
      	<%= form_for VideoUpload.new, :url => "/video_uploads/create/#{@publication.id}", :html => { :multipart => true, :id => "videoupload"  } do |f| %>
      	  <span class="btn btn-md btn-success fileinput-button" id="video_upload_file_container">
      		<span>Seleccionar Video</span>
              <%= f.file_field :video, :id => "video_upload_file" %>
            </span>
          </span>
      	  <%= f.submit 'Guardar Video', :id => "video_upload_button", :class => 'btn btn-md btn-primary videoButton', :style => "display:none;" %>
      	<% end %>
      <% end %>
	  <% if policy(@publication).delete_video? %>
      	<%= form_for VideoUpload.new, :url => "/video_uploads/destroy/#{@publication.video_uploads.first.id}", :html => { :multipart => true, :id => "videoupload"  } do |f| %>
      	  <%= f.submit 'Eliminar Video', :id => "video_upload_button", :class => 'btn btn-md btn-danger videoButton', :data => { :confirm => '¿Esta usted seguro que quiere eliminar el video de la publicación?' } %>
      	<% end %>
      <% end %>

      <%= link_to "Imagenes", uploads_publication_path(@publication), :class => 'btn btn-md btn-default' %>
      

      <%= link_to "Volver",  publications_path, :class => 'btn btn-md btn-default'  %>
      <%= link_to "Editar", edit_publication_path(@publication), :class => 'btn btn-md btn-default' %>
      

      <%= link_to "Eliminar", publication_path(@publication), :method => 'delete',              :data => { :confirm => 'Está seguro que desea eliminar la publicación?' }, :class => 'btn btn-md btn-danger' %>
    
  </div>
</div>
<script type="text/javascript" >
  $( document ).ready(function() {
      $('.carousel').carousel();
      //attach to file chosen event
      $("#video_upload_file").change(function (){
      	onfileSelected();
      });
  });
  
  function showPhotos(){
  	$('#videoContainer').hide();
  	$('#myCarousel').show();
  }
  
  function showVideo(){
  	$('#myCarousel').hide();
  	$('#videoContainer').show();
  }
 
  function validVideoFormat(filename){
  	// a bit ugly validation
  	fileExtension = $("#video_upload_file").val().split('.').pop();
  	return (fileExtension == "mp4" || fileExtension == "mkv");
  }
 
  function onfileSelected(){
  	filename = $("#video_upload_file").val().split('\\').pop();
  	if (validVideoFormat(filename)){
	  	$("#video_upload_file").hide();
	  	$("#video_upload_file_container").hide();
	  	$("#video_upload_button").show();
	  	$("#video_upload_button").attr("title", filename);
  	}else{
  		alert('Formato de video invalido. Seleccione un video con formato mp4 o mkv');
  	}
  }

</script>